// angular-workspace/projects/component-library/standalone/src/directives/my-input.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Injector,
  NgZone,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import type {
  Components,
  InputChangeEventDetail,
  InputInputEventDetail,
} from 'stencil-library';

import { ProxyCmp, proxyOutputs } from './angular-component-lib/utils';
import { defineCustomElement } from 'stencil-library/components/my-input';
import { ValueAccessor } from 'projects/component-library/src/directives/control-value-accessors';

const INPUT_INPUTS = ['disabled', 'required', 'type', 'value'];

const accessorProvider = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: /*@__PURE__*/ forwardRef(() => MyInput),
  multi: true,
};

@ProxyCmp({
  defineCustomElementFn: defineCustomElement,
  inputs: INPUT_INPUTS,
  methods: ['setFocus', 'getInputElement'],
})
@Component({
  selector: 'my-input',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  // eslint-disable-next-line @angular-eslint/no-inputs-metadata-property
  inputs: INPUT_INPUTS,
  providers: [accessorProvider],
  standalone: true,
})
export class MyInput extends ValueAccessor {
  protected el: HTMLElement;
  constructor(
    c: ChangeDetectorRef,
    r: ElementRef,
    protected z: NgZone,
    injector: Injector
  ) {
    super(injector, r);
    c.detach();
    this.el = r.nativeElement;
    proxyOutputs(this, this.el, ['myInput', 'myChange', 'myBlur', 'myFocus']);
  }

  @HostListener('myInput', ['$event.target'])
  handleMyInput(el: HTMLMyInputElement): void {
    this.handleValueChange(el, el.value);
  }

  override registerOnChange(fn: (_: any) => void): void {
    super.registerOnChange((value: string) => {
      if (this.type === 'number') {
        /**
         * If the input type is `number`, we need to convert the value to a number
         * when the value is not empty. If the value is empty, we want to treat
         * the value as null.
         */
        fn(value === '' ? null : parseFloat(value));
      } else {
        fn(value);
      }
    });
  }
}

export declare interface MyInput extends Components.MyInput {
  /**
   * The `myInput` event is fired each time the user modifies the input's value.
Unlike the `myChange` event, the `myInput` event is fired for each alteration
to the input's value. This typically happens for each keystroke as the user types.

For elements that accept text input (`type=text`, `type=tel`, etc.), the interface
is [`InputEvent`](https://developer.mozilla.org/en-US/docs/Web/API/InputEvent); for others,
the interface is [`Event`](https://developer.mozilla.org/en-US/docs/Web/API/Event). If
the input is cleared on edit, the type is `null`.
   */
  myInput: EventEmitter<CustomEvent<InputInputEventDetail>>;
  /**
   * The `myChange` event is fired when the user modifies the input's value.
Unlike the `myInput` event, the `myChange` event is only fired when changes
are committed, not as the user types.

Depending on the way the users interacts with the element, the `myChange`
event fires at a different moment:
- When the user commits the change explicitly (e.g. by selecting a date
from a date picker for `<my-input type="date">`, pressing the "Enter" key, etc.).
- When the element loses focus after its value has changed: for elements
where the user's interaction is typing.
   */
  myChange: EventEmitter<CustomEvent<InputChangeEventDetail>>;
  /**
   * Emitted when the input loses focus.
   */
  myBlur: EventEmitter<CustomEvent<FocusEvent>>;
  /**
   * Emitted when the input has focus.
   */
  myFocus: EventEmitter<CustomEvent<FocusEvent>>;
}

// stencil-library/src/components/my-input/my-input.tsx
import type { EventEmitter } from '@stencil/core';
import { Component, Element, Event, Host, Prop, Watch, h } from '@stencil/core';
import type { InputChangeEventDetail, InputInputEventDetail } from './input-interface';
import { InputType } from './input-type';

@Component({
  tag: 'my-input',
  styleUrl: 'my-input.css',
  shadow: true,
})
export class MyInput {
  private nativeInput?: HTMLInputElement;

  @Element() el!: HTMLMyInputElement;

  /**
   * If `true`, the user cannot interact with the input.
   */
  @Prop() disabled = false;

  /**
   * If `true`, the user must fill in a value before submitting a form.
   */
  @Prop() required = false;

  /**
   * The type of control to display. The default type is text.
   */
  @Prop() type: InputType = 'text';

  /**
   * The value of the input.
   */
  @Prop({ mutable: true }) value?: string | number | null = '';

  /**
   * The `myInput` event is fired each time the user modifies the input's value.
   * Unlike the `myChange` event, the `myInput` event is fired for each alteration
   * to the input's value. This typically happens for each keystroke as the user types.
   *
   * For elements that accept text input (`type=text`, `type=tel`, etc.), the interface
   * is [`InputEvent`](https://developer.mozilla.org/en-US/docs/Web/API/InputEvent); for others,
   * the interface is [`Event`](https://developer.mozilla.org/en-US/docs/Web/API/Event). If
   * the input is cleared on edit, the type is `null`.
   */
  @Event() myInput!: EventEmitter<InputInputEventDetail>;

  /**
   * The `myChange` event is fired when the user modifies the input's value.
   * Unlike the `myInput` event, the `myChange` event is only fired when changes
   * are committed, not as the user types.
   *
   * Depending on the way the users interacts with the element, the `myChange`
   * event fires at a different moment:
   * - When the user commits the change explicitly (e.g. by selecting a date
   * from a date picker for `<my-input type="date">`, pressing the "Enter" key, etc.).
   * - When the element loses focus after its value has changed: for elements
   * where the user's interaction is typing.
   */
  @Event() myChange!: EventEmitter<InputChangeEventDetail>;

  /**
   * Emitted when the input loses focus.
   */
  @Event() myBlur!: EventEmitter<FocusEvent>;

  /**
   * Emitted when the input has focus.
   */
  @Event() myFocus!: EventEmitter<FocusEvent>;

  /**
   * Update the native input element when the value changes
   */
  @Watch('value')
  protected valueChanged() {
    const nativeInput = this.nativeInput;
    const value = this.getValue();
    if (nativeInput && nativeInput.value !== value) {
      nativeInput.value = value;
    }
  }

  /**
   * Emits an `myChange` event.
   *
   * This API should be called for user committed changes.
   * This API should not be used for external value changes.
   */
  private emitValueChange(event?: Event) {
    const { value } = this;
    // Checks for both null and undefined values
    const newValue = value == null ? value : value.toString();
    this.myChange.emit({ value: newValue as any, event });
  }

  /**
   * Emits an `myInput` event.
   */
  private emitInputChange(event?: Event) {
    const { value } = this;

    // Checks for both null and undefined values
    const newValue = value == null ? value : value.toString();
    this.myInput.emit({ value: newValue as any, event });
  }

  private getValue(): string {
    return typeof this.value === 'number' ? this.value.toString() : (this.value || '').toString();
  }

  private onInput = (ev: InputEvent | Event) => {
    const input = ev.target as HTMLInputElement | null;
    if (input) {
      this.value = input.value || '';
    }
    this.emitInputChange(ev);
  };

  private onChange = (ev: Event) => {
    this.emitValueChange(ev);
  };

  private onBlur = (ev: FocusEvent) => {
    this.myBlur.emit(ev);
  };

  private onFocus = (ev: FocusEvent) => {
    this.myFocus.emit(ev);
  };

  private renderInput() {
    const { disabled } = this;
    const value = this.getValue();

    return (
      <Host>
        <input
          ref={input => (this.nativeInput = input)}
          disabled={disabled}
          required={this.required}
          type={this.type}
          value={value}
          onInput={this.onInput}
          onChange={this.onChange}
          onBlur={this.onBlur}
          onFocus={this.onFocus}
        />
      </Host>
    );
  }

  render() {
    return this.renderInput();
  }
}
